In [ ]:
#Avec une liste python classique
notes = [12, 15, 8, 26]
notes_plus_2 = [n + 2 for n in notes] #il faut une boucle/ comprehension
print(notes_plus_2)


[14, 17, 10, 28]


In [ ]:
#Avec Numpy
import numpy as np

notes = np.array([12, 15, 8, 20])
notes_plus_2 = notes + 2 #operaiton directe sur le tableau
print(notes_plus_2)
#Les operations s'appliquent automatiquement a tous les elements d'un coup on appelle ca une vectorisation
#beaucoup plus rapide pour de grandes quantites de donnees

[14 17 10 22]


In [ ]:
import numpy as np

#creer un tableau numpy
tableau = np.array([1, 2, 3, 4, 5])
print(tableau)
print(type(tableau))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#operations mathematiques vectorisees

nombres = np.array([1, 2, 3, 4, 5])
print(nombres + 10)
print(nombres * 2)
print(nombres ** 2)
print(nombres)

[11 12 13 14 15]
[ 2  4  6  8 10]
[ 1  4  9 16 25]
[1 2 3 4 5]


In [ ]:
#statistiques instantannees

notes = np.array([12, 15, 8, 20, 14])

print(notes.mean()) #moyenne
print(notes.max())  #max
print(notes.min())  #min
print(notes.std())  #ecart-type
print(notes.sum())  #somme

13.8
20
8
3.919183588453085
69


In [ ]:
#filtrer un tableau
notes = np.array([12, 15, 8, 20, 14])

notes_superieures_10 = notes[notes > 10]
print(notes_superieures_10)

[12 15 20 14]


In [ ]:
#Exercice

import numpy as np

temperatures = np.array([18, 22, 25, 19, 30, 15, 28])

print(temperatures.mean()) #temperature moyenne de la semaine
print(temperatures.max())
print(temperatures.min())
#temperature maximal et minimale
temperatures_fahrenheit = (temperatures * 9/5 + 32)
print(temperatures_fahrenheit)
temperatures_superieures_20 = temperatures[temperatures > 20]
print(temperatures_superieures_20)

22.428571428571427
30
15
[64.4 71.6 77.  66.2 86.  59.  82.4]
[22 25 30 28]


In [ ]:
#tableau a 2 dimensions (matrices)
#creer une matrice

import numpy as np

matrice = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrice)

print(matrice.shape) #(nombre de ligne et nomre de colonne)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
#acceder a un element precis

print(matrice[0, 0])
print(matrice[1, 2])
print(matrice[2, 0])

1
6
7


In [ ]:
#acceder a une ligne ou une colonne entiere
print(matrice[0]) # premiere ligne
print(matrice[:, 0]) #premiere colonne
print(matrice[:, 1])  #deuxieme colonne
print(matrice[1, :])
print(matrice[1])

[1 2 3]
[1 4 7]
[2 5 8]
[4 5 6]
[4 5 6]


In [ ]:
#operation sur les matrices
print(matrice.sum())
print(matrice.sum(axis=0))  #somme par colonne
print(matrice.sum(axis=1))  #somme par ligne
print(matrice.mean()) #fait la moyenne de tous les elements

45
[12 15 18]
[ 6 15 24]
5.0


In [ ]:
#exercice

import numpy as np

notes = np.array([
    [12, 15, 8, 20],
    [18, 14, 16, 10],
    [9, 11, 13, 17]
])

#affiche la forme shape de ce tableau
print(notes.shape)
#affiche les notes du deuxieme etudiants uniquement
print(notes[1])
#affiche tous les notes de la 3 eme matiere
print(notes[:, 2])
#calcule la moyenne de chaque etudiant
print(notes.mean(axis=1))
#calcul de la moyenne de chaque matiere
print(notes.mean(axis=0))

(3, 4)
[18 14 16 10]
[ 8 16 13]
[13.75 14.5  12.5 ]
[13.         13.33333333 12.33333333 15.66666667]


In [ ]:
#Pandas

import pandas as pd

data = {
    'nom': ['Alicia', 'Bob', 'Chloe'],
    'age': [25, 30, 22],
    'ville': ['Antananarivo', 'Lyon', 'Paris']
}

df = pd.DataFrame(data)
print(df)

      nom  age         ville
0  Alicia   25  Antananarivo
1     Bob   30          Lyon
2   Chloe   22         Paris


In [ ]:
#print(df.head())  #affiche les 5 premieres lignes
#print(df.shape) #(noombre de ligne et de colonne)
#print(df.columns) #liste des noms de colonnes
#print(df.info())  #types de donnees + valeurs manquantes
print(df.describe())  #statistiques sur les colonnes numeriques


             age
count   3.000000
mean   25.666667
std     4.041452
min    22.000000
25%    23.500000
50%    25.000000
75%    27.500000
max    30.000000


In [ ]:
print(df['nom'])
print(df['age'].mean())

0    Alicia
1       Bob
2     Chloe
Name: nom, dtype: object
25.666666666666668


In [ ]:
print(df[['nom', 'age']])

      nom  age
0  Alicia   25
1     Bob   30
2   Chloe   22


In [ ]:
#Exercice

import pandas as pd

data = {
    'produit': ['Ordinateur', 'Souris', 'Clavier', 'Ecran', 'Casque'],
    'prix': [899, 25, 45, 199, 79],
    'stock': [12, 150, 80, 30, 60]
}

#Creer le dataframe df a partir de ce dictionnaire
df = pd.DataFrame(data)
print(df)

#affiche les info generale
df.info()

#affiche le prix moyens de tous les produits
print(df['produit'])
print(df['prix'].mean())

#affiche uniquement les colonnes "produits" et "prix"
print(df[['produit', 'prix']])

#affiche le produit qui a le stock le plus eleve
print(df.loc[df['stock'].idxmax()])


      produit  prix  stock
0  Ordinateur   899     12
1      Souris    25    150
2     Clavier    45     80
3       Ecran   199     30
4      Casque    79     60
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   produit  5 non-null      object
 1   prix     5 non-null      int64 
 2   stock    5 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes
None
0    Ordinateur
1        Souris
2       Clavier
3         Ecran
4        Casque
Name: produit, dtype: object
249.4
      produit  prix
0  Ordinateur   899
1      Souris    25
2     Clavier    45
3       Ecran   199
4      Casque    79
produit    Souris
prix           25
stock         150
Name: 1, dtype: object


In [ ]:
!git config --global user.email "aliciaandriantsara"
!git config --global user.name "aliciaandriantsara"

In [ ]:
!ls data-science-learning
!pwd
!ls

ls: cannot access 'data-science-learning': No such file or directory
/content
sample_data


In [ ]:
from google.colab import userdata
GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')
USERNAME = "aliciaandriantsara"
REPO = "data-science-learning"



In [ ]:
%cd /content/
!git clone https://{GITHUB_TOKEN}@github.com/{USERNAME}/{REPO}.git
%cd /content/{REPO}
!ls

/content
Cloning into 'data-science-learning'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 9 (delta 1), reused 9 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (9/9), 11.01 KiB | 11.01 MiB/s, done.
Resolving deltas: 100% (1/1), done.
/content/data-science-learning
00-python-zero.ipynb  test.txt


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

!find /content/drive/MyDrive -name "01-numpy-pandas.ipynb"

Mounted at /content/drive
/content/drive/MyDrive/Colab Notebooks/01-numpy-pandas.ipynb


In [ ]:
!cp "/content/drive/MyDrive/Colab Notebooks/01-numpy-pandas.ipynb" /content/data-science-learning
!ls /content/data-science-learning

/content/data-science-learning


In [ ]:
%cd /content/data-science-learning

[Errno 20] Not a directory: '/content/data-science-learning'
/content


In [ ]:
!ls -la /content/
!file /content/data-science-learning

total 40
drwxr-xr-x 1 root root  4096 Sep  1 10:49 .
drwxr-xr-x 1 root root  4096 Sep  1 10:26 ..
drwxr-xr-x 4 root root  4096 Aug 24 13:21 .config
-rw------- 1 root root 17281 Sep  1 10:49 data-science-learning
drwx------ 5 root root  4096 Sep  1 10:46 drive
drwxr-xr-x 1 root root  4096 Aug 24 13:21 sample_data
/content/data-science-learning: JSON data


In [ ]:
%cd /content
!rm -f /content/data-science-learning

/content


In [ ]:
from google.colab import userdata
GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')
USERNAME = "aliciaandriantsara"
REPO = "data-science-learning"

!git clone https://{GITHUB_TOKEN}@github.com/{USERNAME}/{REPO}.git
!ls /content/data-science-learning

Cloning into 'data-science-learning'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 9 (delta 1), reused 9 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (9/9), 11.01 KiB | 11.01 MiB/s, done.
Resolving deltas: 100% (1/1), done.
00-python-zero.ipynb  test.txt


In [ ]:
!cp "/content/drive/MyDrive/Colab Notebooks/01-numpy-pandas.ipynb" /content/data-science-learning/
!ls /content/data-science-learning

00-python-zero.ipynb  01-numpy-pandas.ipynb  test.txt


In [ ]:
%cd /content/data-science-learning
!git config --global user.email "aliciaandriantsara@gmail.com"
!git config --global user.name "aliciaandriantsara"
!git add .
!git commit -m "Phase 1 : NumPy et Pandas - bases"
!git push

/content/data-science-learning
[main 37c2a9c] Phase 1 : NumPy et Pandas - bases
 1 file changed, 1 insertion(+)
 create mode 100644 01-numpy-pandas.ipynb
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 4.92 KiB | 4.92 MiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/aliciaandriantsara/data-science-learning.git
   1783259..37c2a9c  main -> main


In [ ]:
#filtrer avec une condition simple

import pandas as pd

data = {
    'produit': ['Ordinateur', 'Souris', 'Clavier', 'Ecran', 'Casque'],
    'prix': [899, 25, 45, 199, 79],
    'stock': [12, 150, 80, 20, 60]
}

df = pd.DataFrame(data)

#produit dont le prix est superieur a 50
#df['prix'] cree une colonne de True/False
#df garde uniquement les lignes ou c'est true
produits_chers = df[df['prix'] > 50]
print(produits_chers)

      produit  prix  stock
0  Ordinateur   899     12
3       Ecran   199     20
4      Casque    79     60


In [ ]:
#combiner plusieurs conditions

#prix > 50 ET stock < 100
resultat = df[(df['prix'] > 50) & (df['stock'] < 100)]
print(resultat)

#prix < 50 ou stock > 100
resultat2 = df[(df['prix'] < 50) | (df['stock'] > 100)]
print(resultat2)

      produit  prix  stock
0  Ordinateur   899     12
3       Ecran   199     20
4      Casque    79     60
   produit  prix  stock
1   Souris    25    150
2  Clavier    45     80


In [ ]:
#Filtrer du texte

#egalite exacte
print(df[df['produit'] == 'Souris'])

#contient une sous-chaine
print(df[df['produit'].str.contains('a')])

  produit  prix  stock
1  Souris    25    150
      produit  prix  stock
0  Ordinateur   899     12
2     Clavier    45     80
3       Ecran   199     20
4      Casque    79     60


In [ ]:
#Verifier si une valeur est dans une liste
produits_selection = df[df['produit'].isin(['Souris', 'Clavier'])]
print(produits_selection)

   produit  prix  stock
1   Souris    25    150
2  Clavier    45     80


In [ ]:
import pandas as pd

data = {
    'nom': ['Alicia', 'Bob', 'Chloe', 'David', 'Eva'],
    'age': [25, 34, 22, 45, 29],
    'ville': ['Antananarivo', 'Lyon', 'Paris', 'Lyon', 'Antananarivo'],
    'salaire': [3200, 2800, 3900, 4100, 3500]
}
df = pd.DataFrame(data)

plus_25 = df[df['age'] > 25]
print(plus_25)

habite_a_lyon = df[df['ville'] == 'Lyon']
print(habite_a_lyon)

plus_25_et_gagne_plus_3000 = df[(df['ville'] == 'Lyon') & (df['salaire'] > 3000)]
print(plus_25_et_gagne_plus_3000)

lyon_ou_paris = df[(df['age'] > 25 ) | (df['ville'] == 'Paris')]
print(lyon_ou_paris)

habitant_Antananarivo_ou_Paris = df[(df['ville'].isin(['Antananarivo', 'Paris']))]
print(habitant_Antananarivo_ou_Paris)

     nom  age         ville  salaire
1    Bob   34          Lyon     2800
3  David   45          Lyon     4100
4    Eva   29  Antananarivo     3500
     nom  age ville  salaire
1    Bob   34  Lyon     2800
3  David   45  Lyon     4100
     nom  age ville  salaire
3  David   45  Lyon     4100
     nom  age         ville  salaire
1    Bob   34          Lyon     2800
2  Chloe   22         Paris     3900
3  David   45          Lyon     4100
4    Eva   29  Antananarivo     3500
      nom  age         ville  salaire
0  Alicia   25  Antananarivo     3200
2   Chloe   22         Paris     3900
4     Eva   29  Antananarivo     3500


In [ ]:
#nettoyage de donnees
import pandas as pd
import numpy as np

data = {
    'num': ['Alicia', 'Bob', 'Choe', 'David', 'Eva'],
    'age': [25, np.nan, 22, 45, np.nan],
    'salaire': [3200, 2800, np.nan, 4100, 3500]
}

df = pd.DataFrame(data)
print(df)
#np.nan la valeur manquante la facon dont pandas represente une valeur manquante

      num   age  salaire
0  Alicia  25.0   3200.0
1     Bob   NaN   2800.0
2    Choe  22.0      NaN
3   David  45.0   4100.0
4     Eva   NaN   3500.0


In [ ]:
print(df.isna())  #tableau de true or false pour chaque cellule
print(df.isna().sum())  #nombre de valeur manquante par colonne

     num    age  salaire
0  False  False    False
1  False   True    False
2  False  False     True
3  False  False    False
4  False   True    False
num        0
age        2
salaire    1
dtype: int64


In [ ]:
#supprimer les lignes avec les valeurs manquantes
df_sans_na = df.dropna()
print(df_sans_na)

      num   age  salaire
0  Alicia  25.0   3200.0
3   David  45.0   4100.0


In [ ]:
#remplacer les valeurs manquantes
df['age'] = df['age'].fillna(0)
#remplacer par une valeur fixe

#remplacer par la moyenne de la colonne
df['salaire'] = df['salaire'].fillna(df['salaire'].mean())

print(df)


      num   age  salaire
0  Alicia  25.0   3200.0
1     Bob   0.0   2800.0
2    Choe  22.0   3400.0
3   David  45.0   4100.0
4     Eva   0.0   3500.0


In [ ]:
#detecter et supprimer les doublons

data2 = {
    'nom': ['Alicia', 'Bob', 'Alicia', 'Chloe'],
    'age': [25, 34, 25, 22]
}
df2 = pd.DataFrame(data2)

print(df2.duplicated())
print(df2.drop_duplicates())


0    False
1    False
2     True
3    False
dtype: bool
      nom  age
0  Alicia   25
1     Bob   34
3   Chloe   22


In [ ]:
#verifier et corriger les types de donees
#df.info()

#convertir une colonne en un autre type
#df['age'] = df['age'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   num      5 non-null      object 
 1   age      5 non-null      int64  
 2   salaire  5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes


In [3]:
import pandas as pd
import numpy as np

data = {
    'produit': ['Ordinateur', 'Souris', 'Clavier', 'Souris', 'Ecran', None],
    'prix': [899, 25, np.nan, 25, 199, 79],
    'stock': [12, 150, 80, 150, np.nan, 60]
}
df = pd.DataFrame(data)

#affiche le nombre de valeurs manquantes par colonne
print(df.isna().sum())

#remplace les valeurs manquantes de prix par la moyenne de la colonne
df['prix'] = df['prix'].fillna(df['prix'].mean())
print(df)

#remplacer les valeurs manquantes de stock par 0
df['stock'] = df['stock'].fillna(0)
print(df)

#supprime les lignes ou produit est manquant
df = df.dropna(subset=['produit'])

#detecte et supprime les doublons
print(df.duplicated())
print(df.drop_duplicates())

produit    1
prix       1
stock      1
dtype: int64
      produit   prix  stock
0  Ordinateur  899.0   12.0
1      Souris   25.0  150.0
2     Clavier  245.4   80.0
3      Souris   25.0  150.0
4       Ecran  199.0    NaN
5        None   79.0   60.0
      produit   prix  stock
0  Ordinateur  899.0   12.0
1      Souris   25.0  150.0
2     Clavier  245.4   80.0
3      Souris   25.0  150.0
4       Ecran  199.0    0.0
5        None   79.0   60.0
0    False
1    False
2    False
3     True
4    False
dtype: bool
      produit   prix  stock
0  Ordinateur  899.0   12.0
1      Souris   25.0  150.0
2     Clavier  245.4   80.0
4       Ecran  199.0    0.0


In [4]:
!ls /content/data-science-learning


ls: cannot access '/content/data-science-learning': No such file or directory


In [5]:
from google.colab import userdata
GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')
USERNAME = "aliciaandriantsara"
REPO = "data-science-learning"

%cd /content
!git clone https://{GITHUB_TOKEN}@github.com/{USERNAME}/{REPO}.git
%cd /content/{REPO}

/content
Cloning into 'data-science-learning'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 12 (delta 2), reused 11 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (12/12), 15.83 KiB | 415.00 KiB/s, done.
Resolving deltas: 100% (2/2), done.
/content/data-science-learning


In [7]:
from google.colab import drive
drive.mount('/content/drive')

!cp "/content/drive/MyDrive/Colab Noteboooks/01-numpy-pandas.ipynb" /content/data-science-learning/
!ls /content/data-science-learning


Mounted at /content/drive
cp: cannot stat '/content/drive/MyDrive/Colab Noteboooks/01-numpy-pandas.ipynb': No such file or directory
00-python-zero.ipynb  01-numpy-pandas.ipynb  test.txt
