In [1]:
#Avec une liste python classique
notes = [12, 15, 8, 26]
notes_plus_2 = [n + 2 for n in notes] #il faut une boucle/ comprehension
print(notes_plus_2)


[14, 17, 10, 28]


In [3]:
#Avec Numpy
import numpy as np

notes = np.array([12, 15, 8, 20])
notes_plus_2 = notes + 2 #operaiton directe sur le tableau
print(notes_plus_2)
#Les operations s'appliquent automatiquement a tous les elements d'un coup on appelle ca une vectorisation
#beaucoup plus rapide pour de grandes quantites de donnees

[14 17 10 22]


In [4]:
import numpy as np

#creer un tableau numpy
tableau = np.array([1, 2, 3, 4, 5])
print(tableau)
print(type(tableau))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
#operations mathematiques vectorisees

nombres = np.array([1, 2, 3, 4, 5])
print(nombres + 10)
print(nombres * 2)
print(nombres ** 2)
print(nombres)

[11 12 13 14 15]
[ 2  4  6  8 10]
[ 1  4  9 16 25]
[1 2 3 4 5]


In [7]:
#statistiques instantannees

notes = np.array([12, 15, 8, 20, 14])

print(notes.mean()) #moyenne
print(notes.max())  #max
print(notes.min())  #min
print(notes.std())  #ecart-type
print(notes.sum())  #somme

13.8
20
8
3.919183588453085
69


In [8]:
#filtrer un tableau
notes = np.array([12, 15, 8, 20, 14])

notes_superieures_10 = notes[notes > 10]
print(notes_superieures_10)

[12 15 20 14]


In [10]:
#Exercice

import numpy as np

temperatures = np.array([18, 22, 25, 19, 30, 15, 28])

print(temperatures.mean()) #temperature moyenne de la semaine
print(temperatures.max())
print(temperatures.min())
#temperature maximal et minimale
temperatures_fahrenheit = (temperatures * 9/5 + 32)
print(temperatures_fahrenheit)
temperatures_superieures_20 = temperatures[temperatures > 20]
print(temperatures_superieures_20)

22.428571428571427
30
15
[64.4 71.6 77.  66.2 86.  59.  82.4]
[22 25 30 28]


In [12]:
#tableau a 2 dimensions (matrices)
#creer une matrice

import numpy as np

matrice = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrice)

print(matrice.shape) #(nombre de ligne et nomre de colonne)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [13]:
#acceder a un element precis

print(matrice[0, 0])
print(matrice[1, 2])
print(matrice[2, 0])

1
6
7


In [17]:
#acceder a une ligne ou une colonne entiere
print(matrice[0]) # premiere ligne
print(matrice[:, 0]) #premiere colonne
print(matrice[:, 1])  #deuxieme colonne
print(matrice[1, :])
print(matrice[1])

[1 2 3]
[1 4 7]
[2 5 8]
[4 5 6]
[4 5 6]


In [19]:
#operation sur les matrices
print(matrice.sum())
print(matrice.sum(axis=0))  #somme par colonne
print(matrice.sum(axis=1))  #somme par ligne
print(matrice.mean()) #fait la moyenne de tous les elements

45
[12 15 18]
[ 6 15 24]
5.0


In [27]:
#exercice

import numpy as np

notes = np.array([
    [12, 15, 8, 20],
    [18, 14, 16, 10],
    [9, 11, 13, 17]
])

#affiche la forme shape de ce tableau
print(notes.shape)
#affiche les notes du deuxieme etudiants uniquement
print(notes[1])
#affiche tous les notes de la 3 eme matiere
print(notes[:, 2])
#calcule la moyenne de chaque etudiant
print(notes.mean(axis=1))
#calcul de la moyenne de chaque matiere
print(notes.mean(axis=0))

(3, 4)
[18 14 16 10]
[ 8 16 13]
[13.75 14.5  12.5 ]
[13.         13.33333333 12.33333333 15.66666667]


In [4]:
#Pandas

import pandas as pd

data = {
    'nom': ['Alicia', 'Bob', 'Chloe'],
    'age': [25, 30, 22],
    'ville': ['Antananarivo', 'Lyon', 'Paris']
}

df = pd.DataFrame(data)
print(df)

      nom  age         ville
0  Alicia   25  Antananarivo
1     Bob   30          Lyon
2   Chloe   22         Paris


In [11]:
#print(df.head())  #affiche les 5 premieres lignes
#print(df.shape) #(noombre de ligne et de colonne)
#print(df.columns) #liste des noms de colonnes
#print(df.info())  #types de donnees + valeurs manquantes
print(df.describe())  #statistiques sur les colonnes numeriques


             age
count   3.000000
mean   25.666667
std     4.041452
min    22.000000
25%    23.500000
50%    25.000000
75%    27.500000
max    30.000000


In [14]:
print(df['nom'])
print(df['age'].mean())

0    Alicia
1       Bob
2     Chloe
Name: nom, dtype: object
25.666666666666668


In [18]:
print(df[['nom', 'age']])

      nom  age
0  Alicia   25
1     Bob   30
2   Chloe   22


In [43]:
#Exercice

import pandas as pd

data = {
    'produit': ['Ordinateur', 'Souris', 'Clavier', 'Ecran', 'Casque'],
    'prix': [899, 25, 45, 199, 79],
    'stock': [12, 150, 80, 30, 60]
}

#Creer le dataframe df a partir de ce dictionnaire
df = pd.DataFrame(data)
print(df)

#affiche les info generale
df.info()

#affiche le prix moyens de tous les produits
print(df['produit'])
print(df['prix'].mean())

#affiche uniquement les colonnes "produits" et "prix"
print(df[['produit', 'prix']])

#affiche le produit qui a le stock le plus eleve
print(df.loc[df['stock'].idxmax()])


      produit  prix  stock
0  Ordinateur   899     12
1      Souris    25    150
2     Clavier    45     80
3       Ecran   199     30
4      Casque    79     60
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   produit  5 non-null      object
 1   prix     5 non-null      int64 
 2   stock    5 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes
None
0    Ordinateur
1        Souris
2       Clavier
3         Ecran
4        Casque
Name: produit, dtype: object
249.4
      produit  prix
0  Ordinateur   899
1      Souris    25
2     Clavier    45
3       Ecran   199
4      Casque    79
produit    Souris
prix           25
stock         150
Name: 1, dtype: object


In [50]:
!git config --global user.email "aliciaandriantsara"
!git config --global user.name "aliciaandriantsara"

In [49]:
!ls data-science-learning
!pwd
!ls

ls: cannot access 'data-science-learning': No such file or directory
/content
sample_data


In [53]:
from google.colab import userdata
GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')
USERNAME = "aliciaandriantsara"
REPO = "data-science-learning"



In [54]:
%cd /content/
!git clone https://{GITHUB_TOKEN}@github.com/{USERNAME}/{REPO}.git
%cd /content/{REPO}
!ls

/content
Cloning into 'data-science-learning'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 9 (delta 1), reused 9 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (9/9), 11.01 KiB | 11.01 MiB/s, done.
Resolving deltas: 100% (1/1), done.
/content/data-science-learning
00-python-zero.ipynb  test.txt


In [1]:
from google.colab import drive
drive.mount('/content/drive')

!find /content/drive/MyDrive -name "01-numpy-pandas.ipynb"

Mounted at /content/drive
/content/drive/MyDrive/Colab Notebooks/01-numpy-pandas.ipynb


In [3]:
!cp "/content/drive/MyDrive/Colab Notebooks/01-numpy-pandas.ipynb" /content/data-science-learning
!ls /content/data-science-learning

/content/data-science-learning


In [5]:
%cd /content/data-science-learning

[Errno 20] Not a directory: '/content/data-science-learning'
/content


In [6]:
!ls -la /content/
!file /content/data-science-learning

total 40
drwxr-xr-x 1 root root  4096 Sep  1 10:49 .
drwxr-xr-x 1 root root  4096 Sep  1 10:26 ..
drwxr-xr-x 4 root root  4096 Aug 24 13:21 .config
-rw------- 1 root root 17281 Sep  1 10:49 data-science-learning
drwx------ 5 root root  4096 Sep  1 10:46 drive
drwxr-xr-x 1 root root  4096 Aug 24 13:21 sample_data
/content/data-science-learning: JSON data


In [ ]:
%cd /content
